[log]
level = "debug"
pretty_json = true
time_on = true
time_format = "2000-01-01 00:00:00"

[database]
dsn = "user=postgres password=postgres host=localhost port=5432 dbname=oj_lab sslmode=disable TimeZone=Asia/Shanghai"

[redis]
hosts = ["localhost:6379"]

[jwt]
secret = "example_secret"
duration = "24h"

[service]
force_console_color = true
auth_on = true
host = "localhost"
port = 8080
ssl_enabled = false
mode = "debug"
swagger_on = true
frontend_dist = "frontend/dist"

[rpc-server]
port = 50051

[minio]
endpoint = "localhost:9000"
access_key_id = "minio-root-user"
secret_access_key = "minio-root-password"
use_ssl = false
bucket_name = "oj-lab-problem-package"
