version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: development
    ports:
      - 5432:5432

  redis-cluster:
    image: grokzen/redis-cluster:6.0.1
    restart: always
    environment:
      - IP=0.0.0.0
    ports:
      - 7000-7005:7000-7005

  # redis:
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - "6379:6379"