version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: development
      POSTGRES_DB: oj_lab
    ports:
      - 5432:5432
  
  # https://hub.docker.com/r/bitnami/minio
  minio:
    image: 'bitnami/minio:latest'
    privileged: true
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password

  redis-cluster:
    image: grokzen/redis-cluster:6.0.1
    restart: always
    environment:
      - IP=0.0.0.0
    ports:
      - 7000-7005:7000-7005

  # redis:
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - "6379:6379"