[log]
level = "debug"

[database]
dsn = "user=postgres password=development host=localhost port=5432 dbname=oj_lab sslmode=disable TimeZone=Asia/Shanghai"

[jwt]
secret = "example_secret"
duration = "24h"

[service]
auth_on = true
port = ":8080"
cookie.age = "24h"
mode = "debug"