[log]
level = "debug"

[database]
dsn = "user=postgres password=development host=localhost port=5432 dbname=oj_lab sslmode=disable TimeZone=Asia/Shanghai"

[jwt]
secret = "example_secret"
duration = "24h"

[service]
auth_on = true
port = ":8080"
cookie.age = "24h"
mode = "debug"

[judger]
host = "http://localhost:8000"

[minio]
endpoint = "localhost:9000"
accessKeyID = "minio-root-user"
secretAccessKey = "minio-root-password"
useSSL = false
bucketName = "oj-lab-problem-package"
