services:
  judger:
    image: ghcr.io/oj-lab/judger:main
    pull_policy: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ENABLE_RCLONE=true
    ports:
      - 8000:8000