name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build Service
      run: go build -o bin/user_service -v user-service/application.go
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Build SQL & Redis Service
      run: docker-compose up -d
      
    - name: SQL Migration
      run: |
        go build -o bin/migrate -v migration/migrate_user.go
        ./bin/migrate config/ini/test.ini
    
    - name: Test
      run: |
        go test -cover -v ./...
